# Rationale and instructions for this GitHub Actions workflow:
# https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#support-fork-repositories-and-dependabot-branches

name: Publish Test Results
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
permissions: {}
jobs:
  test-results:
    name: Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    permissions:
      checks: write
      pull-requests: write
      actions: read
    steps:
      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@8885e273a4343cd7b48eaa72428dea0c3067ea98
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          action_fail: true
          fail_on: "test failures"
          event_file: artifacts/Test Results Event/event.json
          event_name: ${{ github.event.workflow_run.event }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: XSpec Test Results
          comment_mode: always
          files: "testing/xspec-reports/**/*_junit.xml"
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
